class Tick:
    def __init__(self, timestamp: int, price: float, volume: float) -> None: ...

class BarSeries:
    def __repr__(self) -> str: ...

class TickAggregator:
    def __init__(self, interval_secs: int) -> None: ...
    def push_tick(self, tick: Tick) -> None: ...
