class Tick:
    def __init__(self, timestamp: int, price: float, volume: float) -> None: ...

class BarSeries:
    def to_records(self) -> list[list[float]]: ...
    def __len__(self) -> int: ...
    def __repr__(self) -> str: ...

class TickAggregator:
    def __init__(self, interval_secs: int) -> None: ...
    def push_tick(self, tick: Tick) -> None: ...
    def push_ticks(self, ticks: list[Tick]) -> None: ...
    def push_from_arrays(self, timestamps: list[int], prices: list[int], volumes: list[int]) -> None: ...
    def push_from_bytes(self, data: bytes) -> None: ...
    def push_from_numpy(self, timestamps, prices, volumes) -> None: ...
    def push_from_buffer(self, timestamps, prices, volumes) -> None: ...
    def finalize(self) -> BarSeries: ...
    def __repr__(self) -> str: ...
